name: 'Operator-SDK Action'
description: 'GitHub Actions for Operator-SDK build'
author: 'Michael Fornaro <michaelfornaro@gmail.com>'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  image:
    description: 'Image name'
    required: true
  tag:
    description: 'Image tag'
    required: false
  dirPath:
    description: 'Project structure requires build/Dockerfile'
    required: false
outputs:
  image:
    description: 'Built docker image'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.image }}
    - ${{ inputs.tag }}
    - ${{ inputs.dirPath }}
